APP_BRAND_NAME = "Qonic"
APP_DISPLAY_NAME = "Qonic Audio"
APP_DESCRIPTION = "Qonic Audio Converter & Editor"
APP_VERSION = "5.0.0-beta.1"
APP_RELEASE_CHANNEL = "Internal Beta"
APP_PROJECT_CLASSIFICATION = "Personal Software Project"
APP_RELEASE_VERSION = "5.0.0-beta.1"
APP_STAGE = APP_RELEASE_CHANNEL
APP_WINDOW_TITLE = (
    f"{APP_DISPLAY_NAME} v{APP_VERSION} — {APP_RELEASE_CHANNEL}"
)
APP_PACKAGE_BASENAME = f"Qonic_Audio_v{APP_RELEASE_VERSION}"
APP_INSTALLER_BASENAME = f"{APP_PACKAGE_BASENAME}_Setup"
APP_DATA_DIR_NAME = "Qonic Audio"
APP_SPEC_NAME = "Qonic_Audio.spec"
APP_RELEASE_NOTES_NAME = "Release_Notes_v5.0_Internal_Test.md"
